name: plataforma_app
description: Aplicacion de la plataforma de vivenciart

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  #Country Picker
  country_pickers: ^1.3.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0  
  # Functional programming thingies
  dartz: ^0.9.2
  # Remote API - check conexion
  data_connection_checker: ^0.3.4
  # Para operaciones que requieren precision
  decimal: ^0.3.5
  # Para http
  dio: ^3.0.10
  # Value equality
  equatable: ^1.2.5
  #Firebase auth
  firebase_auth: ^0.18.3
  flutter:
    sdk: flutter
  # Flutter Custom Clippers
  flutter_custom_clippers: ^1.1.2
  # Para archivo de ambiente
  flutter_dotenv: ^2.1.0
  #Facebook Sign in
  flutter_facebook_login: ^3.0.0
  # Flutter Local Notification
  flutter_local_notifications: ^3.0.2
  # Localizations
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^1.0.4
  # Manejador de estados  
  flutter_riverpod: ^0.12.1
  #Renderizado y tratamiento de SVGs
  flutter_svg: ^0.19.2+1
  #SVG Provider
  flutter_svg_provider: ^0.1.8
  #Swiper(carousel) for flutter
  flutter_swiper: ^1.1.6
  #Font awesome and Icons
  font_awesome_flutter: ^8.10.0
  # Service locator
  get_it: ^5.0.1
  #Google Sign in
  google_sign_in: ^4.5.6
  # Photo and gallery
  image_picker: ^0.6.7+14
  # Dependency injection
  injectable: ^1.0.5
  # Localizacion
  intl: ^0.16.1
  # Dependencia para la serializacion json (toJson y fromJson) complementaria con json_serializable
  json_annotation: ^3.0.0
  # Liquid Swipe Screen
  liquid_swipe: ^1.5.0
  #ORM
  moor: ^3.4.0
  moor_flutter: ^3.1.0
  # Join functionality on paths
  path: ^1.7.0
  # Path provider for directories
  path_provider: ^1.6.24
  # Para los clientes rest
  retrofit: ^1.3.4+1
  # RxDart add on streams
  rxdart: ^0.25.0
  # Local cache
  shared_preferences: ^0.5.12+4
  # URL Launcher
  url_launcher: ^5.7.10
  # Auto Size Text
  auto_size_text: ^2.1.0

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  # Dependencia para correr generadores de codigo
  build_runner: ^1.0.0
  # Dependencia que simplifica agregar y modificar el launcher icon
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter
  # Dependency injection generator
  injectable_generator: ^1.0.5
  # Dependencia para autogenerar la serializacion json (toJson y fromJson)
  json_serializable: ^3.2.0
  # Analisis de codigo estatico
  lint: ^1.3.0
  # Para pruebas
  mockito: ^4.1.1
  #ORM
  moor_generator: ^3.4.0
  #Para los clientes rest
  retrofit_generator: ^1.4.1+1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/experience_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/env/.env_dev_sergio
    - assets/env/.env_dev_javier
    - assets/env/.env_staging
    - assets/env/.env_production
  fonts:
    - family: Billy
      fonts:
        - asset: assets/fonts/font.ttf
    - family: EvilEmpire
      fonts:
        - asset: assets/fonts/evil_Empire.otf
    - family: FontDoll
      fonts:
        - asset: assets/fonts/font_doll.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: San Francisco
      fonts:
        - asset: assets/fonts/SFUIDisplay-Thin.otf
        - asset: assets/fonts/SFUIDisplay-Regular.otf
        - asset: assets/fonts/SFUIDisplay-Bold.ttf

flutter_intl:
  main_locale: en_US
  enabled: true
